# Collector specific configuration
notes:
  first_part: >
    Internally displaced persons are defined according to [the 1998 Guiding Principles](https://www.internal-displacement.org/internal-displacement/guiding-principles-on-internal-displacement) as people or groups of people who have been forced or obliged to flee or to leave their homes or places of habitual residence, in particular as a result of armed conflict, or to avoid the effects of armed conflict, situations of generalized violence, violations of human rights, or natural or human-made disasters and who have not crossed an international border.
  displacement: >
    "Internally displaced persons - IDPs" refers to the number of people living in displacement as of the end of each year.
  disaster: >
    "Internal displacements (New Displacements)" refers to the number of new cases or incidents of displacement recorded, rather than the number of people displaced. This is done because people may have been displaced more than once.
  last_part: >
    Contains data from IDMC's [Global Internal Displacement Database](http://www.internal-displacement.org/database/displacement-data).

tags:
  - "hxl"
  - "displacement"
  - "internally displaced persons-idp"

indicators:
  - name: "displacement"
    url: "https://helix-tools-api.idmcdb.org/external-api/gidd/conflicts/?format=json&limit=100"
    resourceview: "hdx_resource_view_static.yaml"
    flatten: []
    hxltags:
      iso3: "#country+code"
      country_name: "#country+name"
      year: "#date+year"
      new_displacement: "#affected+idps+ind+new+conflict"
      new_displacement_rounded: ~
      total_displacement: "#affected+idps+ind+total+conflict"
      total_displacement_rounded: ~
    title: "Internal Displacements (New Displacements) – IDPs"
    sort:
      - "year"
      - "iso3"
    tags:
      - "conflict-violence"
  - name: "disaster"
    url: "https://helix-tools-api.idmcdb.org/external-api/gidd/disasters/?format=json&limit=100"
    resourceview: "hdx_resource_view_static_disaster.yaml"
    flatten:
      - glide_numbers
    hxltags:
      iso3: "#country+code"
      country_name: "#country+name"
      year: "#date+year"
      start_date: "#date+start"
      start_date_accuracy: "#accuracy+date+start"
      end_date: "#date+end"
      end_date_accuracy: "#accuracy+date+end"
      event_name: "#event+name"
      hazard_category: "#crisis+category+code"
      hazard_category_name: "#crisis+category+name"
      hazard_sub_category: "#crisis+subcategory+code"
      hazard_sub_category_name: "#crisis+subcategory+name"
      hazard_type: "#crisis+type+code"
      hazard_type_name: "#crisis+type+name"
      hazard_sub_type: "#crisis+subtype+code"
      hazard_subtype_name: "#crisis+subtype+name"
      new_displacement: "#affected+idps+ind+new+disaster"
      new_displacement_rounded: ~
      total_displacement: "#affected+idps+ind+total+disaster"
      total_displacement_rounded: ~
      glide_numbers: "#crisis+code"
    title: "Internal displacements (new displacements) associated with disasters"
    sort:
      - "start_date"
      - "end_date"
      - "iso3"
      - "event_name"
    tags:
      - "natural disasters"

country_dataset:
  name: "IDMC IDP data "
  title: "Internal Displacements (New Displacements) – IDPs"
  quickcharts: "displacement"
