# Collector specific configuration
indicators:
  - name: "displacement_data"
    url: "https://api.idmcdb.org/api/displacement_data/xlsx?ci=IDMCWSHSOLO009&filename=idmc_displacement_all_dataset.xlsx"
    spreadsheet: "https://docs.google.com/spreadsheets/d/e/2PACX-1vRubZgyjd7Az7Vgaxb5lWFpjojmjYZRlcVaVqYBEuEmpIojnuVn0nJG6DAJUaIzn0NdVhAkQuBw5t8q/pub?gid=66420666&single=true&output=csv"
    resourceview: "hdx_resource_view_static.yml"
  - name: "disaster_data"
    url: "https://api.idmcdb.org/api/disaster_data/xlsx?ci=IDMCWSHSOLO009&filename=idmc_disaster_all_dataset.xlsx"
    spreadsheet: "https://docs.google.com/spreadsheets/d/e/2PACX-1vRubZgyjd7Az7Vgaxb5lWFpjojmjYZRlcVaVqYBEuEmpIojnuVn0nJG6DAJUaIzn0NdVhAkQuBw5t8q/pub?gid=0&single=true&output=csv"
    resourceview: "hdx_resource_view_static_disaster.yml"
tags:
  - "hxl"
  - "displacement"
  - "internally displaced persons-idp"
  - "conflict-violence"