# Collector specific configuration
notes:
  first_part: |
    The [Global Internal Displacement Database (GIDD)](http://www.internal-displacement.org/database/displacement-data), maintained by the [Internal Displacement Monitoring Centre (IDMC)](https://www.internal-displacement.org/), provides comprehensive, validated annual estimates of internal displacement worldwide. It defines internally displaced persons (IDPs) in line with the [1998 Guiding Principles](https://www.internal-displacement.org/internal-displacement/guiding-principles-on-internal-displacement/), as people or groups of people who have been forced or obliged to flee or to leave their homes or places of habitual residence, in particular as a result of armed conflict, or to avoid the effects of armed conflict, situations of generalized violence, violations of human rights, or natural or human-made disasters and who have not crossed an international border.


    The GIDD tracks two primary metrics: "People Displaced" or population "Stock" figures, which represent the total number of people living in displacement at year-end, and "New Displacement," which counts new displacement incidents (population Flows) rather than individual people, accounting for potential multiple displacements by the same person. This dataset serves as a crucial resource for understanding long-term trends and validated displacement figures globally. For further detailed information and complete API specifications, users are encouraged to consult the official documentation at https://www.internal-displacement.org/database/api-documentation/.
  displacement: >
    "Internally displaced persons - IDPs" refers to the number of people living in displacement as of the end of each year.
  disaster: >
    "Internal displacements (New Displacements)" refers to the number of new cases or incidents of displacement recorded, rather than the number of people displaced. This is done because people may have been displaced more than once.

tags:
  - "hxl"
  - "displacement"
  - "internally displaced persons-idp"

indicators:
  - name: "displacement"
    url: "https://helix-tools-api.idmcdb.org/external-api/gidd/conflicts/?format=json&limit=100"
    resourceview: "hdx_resource_view_static.yaml"
    hxltags:
      iso3: "#country+code"
      country_name: "#country+name"
      year: "#date+year"
      new_displacement: "#affected+idps+ind+new+conflict"
      new_displacement_rounded: ~
      total_displacement: "#affected+idps+ind+total+conflict"
      total_displacement_rounded: ~
    title: "Internal Displacements (New Displacements) – IDPs"
    sort:
      - "year"
      - "iso3"
    tags:
      - "conflict-violence"
  - name: "disaster"
    url: "https://helix-tools-api.idmcdb.org/external-api/gidd/disasters/?format=json&limit=100"
    resourceview: "hdx_resource_view_static_disaster.yaml"
    hxltags:
      iso3: "#country+code"
      country_name: "#country+name"
      year: "#date+year"
      start_date: "#date+start"
      start_date_accuracy: "#accuracy+date+start"
      end_date: "#date+end"
      end_date_accuracy: "#accuracy+date+end"
      event_name: "#event+name"
      hazard_category: "#crisis+category+code"
      hazard_category_name: "#crisis+category+name"
      hazard_sub_category: "#crisis+subcategory+code"
      hazard_sub_category_name: "#crisis+subcategory+name"
      hazard_type: "#crisis+type+code"
      hazard_type_name: "#crisis+type+name"
      hazard_sub_type: "#crisis+subtype+code"
      hazard_subtype_name: "#crisis+subtype+name"
      new_displacement: "#affected+idps+ind+new+disaster"
      new_displacement_rounded: ~
      total_displacement: "#affected+idps+ind+total+disaster"
      total_displacement_rounded: ~
    title: "Internal displacements (new displacements) associated with disasters"
    sort:
      - "start_date"
      - "end_date"
      - "iso3"
      - "event_name"
    tags:
      - "natural disasters"

country_dataset:
  name: "IDMC IDP data "
  title: "Internal Displacements (New Displacements) – IDPs"
  quickcharts: "displacement"
